### ISSUE TITLE
jp.u.c - blog posts on homepage 

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/jp.ubuntu.com#117]

**Comment by anasereijo** [comment]
note: we need to wait for Base to finish the API

**Comment by nottrobin** [comment]
This is currently blocked by https://github.com/ubuntudesign/base-squad/issues/418, which is not currently planned in this iteration. It's at the top of our backlog, and so will be scheduled for next iteration. But @b-m-f may pick it up earlier if he finishes https://github.com/ubuntudesign/base-squad/issues/420 early.

**Comment by caldav** [comment]
@nottrobin why not using the json feed the blog module is already using?

**Comment by nottrobin** [comment]
@caldav A few reasons. The wordpress API is super slow, and so we cache the responses in blog.ubuntu.com. We'd also like to be able to craft that data that we send to the front-end for performance and computational efficiency.

In general, we think it's much neater if we get to control the endpoint that the client consumes.

**Comment by anasereijo** [comment]
closing this epic as work is being done by the [base squad](https://github.com/ubuntudesign/base-squad/issues/418)
