### ISSUE TITLE
jp.u.c - blog posts on homepage - Build

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/jp.ubuntu.com#119]
Add blog section to the Japanese homepage.

**Comment by pmahnke** [comment]
for an MVP, let's use the get_feed version from u.c

**Comment by anasereijo** [comment]
@anthonydillon I'm "unblocking" this. As Peter's comment, let's use the ubuntu.com version for now

**Comment by anasereijo** [comment]
Closing. @b-m-f is going to do it.
