### ISSUE TITLE
Blog of jp.u.com

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#46]

**Comment by Greggless** [comment]
# Dev tasks
- [ ] Set up `jp.ubuntu.com` tags 
- [ ] Set rule on ubuntu.com to hide articles with `jp.ubuntu.com` tags 
- [ ] Set rule on jp.ubuntu.co/blog to only show articles with `jp.ubuntu.com` tags 
- [ ] Set up jp.ubuntu.com/blog page

**Comment by caldav** [comment]
- The tag name is `lang:jp`
- Feed for posts https://admin.insights.ubuntu.com/wp-json/wp/v2/posts?tags=3184
- To merge before live testing: https://code.launchpad.net/~davidc3/resource-centre/jp-exclude-from-rss/+merge/359035

**Comment by anasereijo** [comment]
@anthonydillon  @tbille can you please estimate this issue?

**Comment by anthonydillon** [comment]
@tbille you are better suited to estimate this work.

**Comment by tbille** [comment]
@anthonydillon @anasereijo we are planning to see what templates needs to be done and then I will close this issue
