### ISSUE TITLE
Homepage - JP.U.COM

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#47]

**Comment by deadlight** [comment]
Copydocs:
- [JP](https://docs.google.com/document/d/1J4zHHJ19ueONPtgj9oHTWGvWRX5JTmHy8VuGy4mygp8/edit)
- [EN](https://docs.google.com/document/d/1oCtGh6I6macNKLKsVfy3SpOqphyja6U8IJ9jMU7eqXo/edit)
