### ISSUE TITLE
Kubernetes - JP.U.COM

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#50]

**Comment by deadlight** [comment]
Copydocs
- [JP](https://docs.google.com/document/d/1t-fQU3HfRNRVoIRjsFJRyDbHq-NvP7YapdnijAqBtNI/edit)
- [EN](https://docs.google.com/document/d/1W07TyJPooa6iCkj8aZSGye8Cn6-VobnUMHSuN38B9s8/edit)
