### ISSUE TITLE
Downloads - JP.U.COM

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#53]

**Comment by deadlight** [comment]
Copydocs
- [JP](https://docs.google.com/document/d/1Oo1RGknik6ohMboaw66HRbpqDOF1sChJGNQrSoyUxio/edit)
- [EN](https://docs.google.com/document/d/157kBpIHzwfnRwLGncAsqyMxTO9AufXRJCZB9TTJ_zu4/edit)
