### ISSUE TITLE
Contact us - JP.U.COM

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#54]

**Comment by deadlight** [comment]
Copydocs
- [JP](https://docs.google.com/document/d/1x_Jimq497nQ8mpy5wKZFexWcc1fWPLYnOi3xQP_ts_4/edit)
- [EN](https://docs.google.com/document/d/13d4NTNoS_nWafa9dZg3vIYZfT4bDiHRdjMVHYrU6iM0/edit)

**Comment by deadlight** [comment]
Form:
https://pages.ubuntu.com/contact-us-jp.html
