### ISSUE TITLE
Thank you - JP.U.COM

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#55]

**Comment by deadlight** [comment]
Copydocs
- [JP](https://docs.google.com/document/d/19XYYdpmWgp_ykb0_DbA5eo6rHlaQ-zGoenkSSTZl4Ls/edit)
- [EN](https://docs.google.com/document/d/1HwP0daLf7NAllRx6vKExG885-_86V5eN-T_lKrKpunc/edit)
