### ISSUE TITLE
Design jp.ubuntu navigation

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#58]
Create designs based on the [UX work](https://github.com/ubuntudesign/web-squad/issues/894#issuecomment-440299023)

**Comment by anasereijo** [comment]
### >990

![990](https://user-images.githubusercontent.com/36884067/49588588-05d73780-f95f-11e8-990e-cf3a813d6057.png)

### >990 Secondary nav (support)

![990 secondary nav support](https://user-images.githubusercontent.com/36884067/49588549-e7713c00-f95e-11e8-9861-39997ba71477.png)


### 989 - 768

![989 - 768](https://user-images.githubusercontent.com/36884067/49588614-1be4f800-f95f-11e8-9201-b3828ebf89f7.png)


### 989 - 768 Secondary nav (support)

![989 - 768 secondary nav support](https://user-images.githubusercontent.com/36884067/49588563-f0faa400-f95e-11e8-8baa-47f09eeaf27c.png)

### <767

![767](https://user-images.githubusercontent.com/36884067/49588643-2dc69b00-f95f-11e8-8d51-71595ada51ce.png)


### <767 Secondary nav (support)

![767 secondary nav support](https://user-images.githubusercontent.com/36884067/49588567-f6f08500-f95e-11e8-98ed-b54b58762424.png)

**Comment by anasereijo** [comment]
@Greggless UX needed 👍

**Comment by Greggless** [comment]
### A quick update
We've accidentally highlighted **Artificial intelligence**, and given that the secondary nav. Enterprise support is 商用サポート 

### Left-to-right is OK
Some quick research says that left-to-right is common when two languages are used together and in context of computerized typesetting.
> Today, the left-to-right direction is dominant in all three languages for horizontal writing: this is due partly to the influence of English and other Western languages to **make it easier to read when the two languages are found together** (for example, on signs at an airport or train station), and partly to the increased use of **computerized typesetting and word processing software**, most of which does not directly support right-to-left layout of East Asian languages.

**Comment by anasereijo** [comment]
@Greggless design is amended 👍 I updated on my previous comment.
