### ISSUE TITLE
Build jp.ubuntu navigation

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#59]
jp.ubuntu's navigation will follow the same pattern as [cn.ubuntu's updated navigation](https://github.com/ubuntudesign/web-squad/issues/921).

**Comment by anasereijo** [comment]
ready to be built. check design [here](https://github.com/canonical-websites/jp.ubuntu.com/issues/58#issuecomment-444884721)

**Comment by Greggless** [comment]
Dropped from iteration 18-19
