### ISSUE TITLE
Review display density for jp.ubuntu.com

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#60]
- [ ] Obtain a sample of translated copy for a page
- [ ] Prepare page demo
- [ ] Review display density with stakeholders and agency

**Comment by Greggless** [comment]
Dropped from iteration 18-49

**Comment by shivjoshi1996** [comment]
Dropped as this will be done alongside the build tasks on the new Japanese website refresh. 
https://github.com/canonical-websites/jp.ubuntu.com/issues/57
