### ISSUE TITLE
jp.ubuntu.com - Design review

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#61]
## Design review
  - [ ] Homepage - 1pt
  - [ ] Openstack - 1pt
  - [ ] Kuberentes - 1pt
  - [ ] AI/ML - 1pt
  - [ ] IoT - 1pt
  - [ ] Enterprise Support - 1pt
  - [ ] Download - 1pt

**Comment by anasereijo** [comment]
@Greggless is this ready to be looked at?

**Comment by Greggless** [comment]
Nope. Next week we'll have something

# 🍔
