### ISSUE TITLE
Menu item is not highlighted when active

### ISSUE THREAD

**Issue by clagom** [canonical-websites/jp.ubuntu.com#83]
## Summary
[list the steps to replicate the issue]
Going on a secondary page, doesn't highlight the active item in the menu

## Current and expected result
The active item should be highlighted in the menu
e.g. OpenStack page, the item in the menu should have the Vanilla underline below?

## Screenshot
<img width="724" alt="52205384-cf3e7000-286e-11e9-9b8e-c45858f0f965" src="https://user-images.githubusercontent.com/1953388/52205780-2729a680-2870-11e9-9b3f-3c974409b8bc.png">

**Comment by pmahnke** [comment]
this was fixed in #84
