### ISSUE TITLE
Japanese ubuntu.com blog - update templates

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/jp.ubuntu.com#87]
implement [design](https://github.com/canonical-websites/jp.ubuntu.com/issues/86)

**Comment by anthonydillon** [comment]
@anasereijo, is this a dip of #46?

**Comment by anasereijo** [comment]
@anthonydillon  we will have some front-end work to be done so that's why I created this issue. Do you think we shouldn't keep it?

**Comment by anasereijo** [comment]
dup

**Comment by anthonydillon** [comment]
Dup?
